server:
  port: ${port:0}

spring:
  application:
    name: movie-service
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: ${MYSQL_PASSWORD}
    url: ${MYSQL_URL2}
    username: ${MYSQL_USERNAME}
  jpa:
    hibernate:
    ddl-auto: create-drop
    show-sql: false


message: hello from movie-service

management:
  endpoints:
    web:
      exposure:
        include: '*'